spring:
  application:
    name: config-server

    cloud:
      config:
        server:
          git:
            uri: https://github.com/luan-alencar/springmicroservices

            # desativar validacao ssl do git
            skip-ssl-validation: true

            # configurar o tempo em seg que o servidor aguardara para adquirir uma conexao HTTP
            timeout: 4

  datasource:
    driver-class-name: org.postgresql.Driver

  http:
    encoding:
      enabled: true
        charset: UTF-8
server:
  port: 8888