server:
  port: 8088

spring:
  application:
    name: gatewayservice
  cloud:
    gateway:
      routes:
        - id: accountmodule, inventorymodule
          uri: lb://account-service, lb://inventory-service
          predicates:
            - Path=/accounts/**
            - Path=/inventories/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream